spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
      routes:
      - id: welcome
        uri: lb://welcome
        predicates:
        - Path=/welcome
      - id: greet
        uri: lb://greet
        predicates:
        - Path=/greet
  boot:
   admin:
    client:
     url: http://localhost:1111/
server:
  port: 8085
  
